fighters = {
    "lancelot": {
        "name": "Lancelot",
        "power": 35,
        "hp": 290,
        "protection": 0,
        "armour": 0,
        "helmet": 0,
        "breastplate": 0,
        "boots": 0,
        "weapon_name": "Metal Sword",
        "weapon_power": 50,
        "potion": None,
    },
    "arthur": {
        "name": "Arthur",
        "power": 45,
        "hp": 75,
        "helmet": 15,
        "breastplate": 20,
        "boots": 10,
        "protection": 0,
        "armour": 0,
        "weapon_name": "Excalibur",
        "weapon_power": 50,
        "potion": None,
    },
    "mordred": {
        "name": "Mordred",
        "power": 30,
        "hp": 90,
        "protection": 0,
        "helmet": 0,
        "breastplate": 15,
        "boots": 10,
        "armour": 0,
        "weapon_name": "Venom",
        "potion": 0,
        "weapon_power": 60,
        "potion_name": "Berserk",
        "potion_power": +15,
        "potion_hp": -5,
        "potion_protection": +10,
    },
    "red_knight": {
        "name": "Red Knight",
        "power": 40,
        "hp": 70,
        "helmet": 0,
        "breastplate": 25,
        "boots": 10,
        "protection": 0,
        "armour": 0,
        "weapon_name": "Sword",
        "weapon_power": 45,
        "potion": 0,
        "potion_name": "Blessing",
        "potion_power": +5,
        "potion_hp": +10,
        "potion_protection": 0,
    }
}
